volumes:
  staticfiles:

services:
  application-backend:
    build: .
    container_name: frictionless-application-backend-django
    env_file:
      - ${ENV_FILE_PATH:-.env}
    environment:
      - ALLOWED_HOSTS=www.frictionless-capture.com frictionless-capture.com
      - CSRF_TRUSTED_ORIGINS=https://www.frictionless-capture.com https://frictionless-capture.com
      - AIRFLOW_HOST=http://airflow-apiserver:8080
    volumes:
      - ./app:/app
      - staticfiles:/app/static
  nginx:
    image: nginx:1.21-alpine
    container_name: frictionless-application-backend-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - staticfiles:/static/application-backend
    depends_on:
      - application-backend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
